# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: saneyates projects
email: 
description: > # this means to ignore newlines until "baseurl:"
  This site showcases some of my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sane8s.github.io/" # the base hostname & protocol for your site
twitter_username: sane8s
github_username:  sane8s

# Build settings
markdown: kramdown
